version: '3.3'

services:
  app_server:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - .:/app
      - ~/.composer/cache:/.composer/cache
      - ~/.npm:/home/application/.npm

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2g
    links:
      - app_server:docker.vm
