version: '3.3'

services:
  app_server:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - .:/app
      - ~/.composer:/.composer
      - ~/.npm:/.npm
    tmpfs:
      - /tmp:mode=1777

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  adminer:
    image: adminer:latest
    links:
      - app_mysql:mysql
