version: '3.7'

networks:
    shopware:

services:
  app_server:
    image: shopware/development:latest
    networks:
      shopware:
        aliases:
          - docker.vm
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - ~/.composer:/.composer
    tmpfs:
      - /tmp:mode=1777

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    networks:
      shopware:
        aliases:
          - mysql

  cypress:
    image: cypress/included:4.4.0
    tty: true
    ipc: host
    environment:
      - CYPRESS_baseUrl=http://docker.vm:8000
      - DISPLAY
    networks:
      shopware:
    volumes:
      - ./vendor/shopware/platform/src/Storefront/Resources/app/storefront/test/e2e:/e2e-Storefront
      - ./vendor/shopware/platform/src/Administration/Resources/app/administration/test/e2e:/e2e-Administration
      # for Cypress to communicate with the X11 server pass this socket file
      # in addition to any other mapped volumes
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/bash

  mailhog:
    image: mailhog/mailhog
    networks:
      shopware:
        aliases:
          - mailhog

  adminer:
    image: adminer:latest
    networks:
      shopware:

  elasticsearch:
    image: elastic/elasticsearch:7.1.1
    networks:
        shopware:
            aliases:
                - elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
