#override defaults for dev
version: "3.7"

services:
  app_server:
    image: shopware/development:local
    build:
      context: dev-ops/docker/containers/app
      args:
        USER_ID: __USER_ID__
        GROUP_ID: __GROUP_ID__
    volumes:
      - __DOCKER_APP_VOLUME_MOUNT__
      - ~/.npm:/.npm
    environment:
      CONTAINER_UID: __USER_ID__
      APPLICATION_UID: __USER_ID__
      APPLICATION_GID: __GROUP_ID__
    ports:
      - "8000:8000"
      - "__DEVPORT__:__DEVPORT__"
      - "8005:8005"
      - "__STOREFRONT_PROXY_PORT__:__STOREFRONT_PROXY_PORT__"
      - "9999:9999"

  app_mysql:
    ports:
      - "4406:3306"
    volumes:
      - ./dev-ops/docker/_volumes/mysql:/mysql-data

  cypress:
    entrypoint: "cypress open --project . --config CYPRESS_baseUrl=${URL}"

  adminer:
    ports:
      - "8001:8080"

  mailhog:
    ports:
      - "8002:8025"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

__DOCKER_APP_VOLUMES__