#override defaults for dev
version: "3.7"

services:
  app_server:
    image: shopware/development:local
    build:
      context: dev-ops/docker/containers/app
      args:
        USER_ID: __USER_ID__
        GROUP_ID: __GROUP_ID__
        IMAGE_VARIANT: __DOCKER_IMAGE_VARIANT__
        PHP_VERSION: __DOCKER_PHP_VERSION__

    volumes:
      - __DOCKER_APP_VOLUME_MOUNT__
      - ~/.npm:/.npm
    environment:
      CONTAINER_UID: __USER_ID__
      APPLICATION_UID: __USER_ID__
      APPLICATION_GID: __GROUP_ID__
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:__DEVPORT__:__DEVPORT__"
      - "127.0.0.1:8005:8005"
      - "127.0.0.1:__STOREFRONT_PROXY_PORT__:__STOREFRONT_PROXY_PORT__"
      - "127.0.0.1:9999:9999"

  app_mysql:
    ports:
      - "127.0.0.1:4406:3306"
    volumes:
      - ./dev-ops/docker/_volumes/mysql:/mysql-data

  adminer:
    ports:
      - "127.0.0.1:8001:8080"

  mailhog:
    ports:
      - "127.0.0.1:8002:8025"

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

__DOCKER_APP_VOLUMES__
